categories:
  sitesetscompat:
    label: "Site sets compat example"

settings:
  site_sets_compat.text:
    label: "Text to show"
    type: string
    default: "Hello, TYPO3 universe!"
    category: sitesetscompat
